[package]
name = "agon-light-emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.2.0"
sdl2 = "0.35"
iz80 = { git = "https://github.com/tomm/ez80.git", rev = "f8ca864e00f2b6b17e560a377a454f1bbe38c936"}