[package]
name = "agon-light-emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35"
agon-cpu-emulator = { git = "https://github.com/tomm/agon-cpu-emulator.git", rev="f65b94333c99706cda98440d26d8525b4960ca77"}
agon-light-vdp = { git = "https://github.com/astralaster/agon-light-vdp.git", rev="de095f450b4682c690ce69d55a45e12175c0f774"}