[package]
name = "agon-light-emulator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.35"
clap = { version = "4.3.1", features = ["derive"] }
agon-cpu-emulator = { git = "https://github.com/tomm/agon-cpu-emulator.git", rev="244177e1c4b4e5db673f9fa16ea79cdd96059542"}
agon-light-vdp = { git = "https://github.com/astralaster/agon-light-vdp.git", rev="48aa5c631a3fc54c12ef9619cf4b01e0dcd77438"}